### ISSUE TITLE
Torch not compiled with CUDA (Windows support?)

### ISSUE THREAD

**Issue by zslittlehelper** [haoheliu/AudioLDM#5]
I followed the instructions but kept getting complaints that torch was not compiled with CUDA support.

I tried switching Torch to the CU variants, but that only resulting in cascading complaints regarding missing DLLs.

Has this repository been tested in a windows environment? (Or am I on a fool's errand?)

**Comment by haoheliu** [comment]
It sounds like you installed PyTorch without CUDA support. https://pytorch.org/ has instructions for how to install pytorch with cuda support. Thanks.

**Comment by zslittlehelper** [comment]
_I'm a newbie to this, so for others peering into this issue..._

The Torch that are automatically installed into the environment don't seem to be the full thing (uncertain how this works). Going to PyTorch, selecting a full CUDA environment (CUDA 11.6 in my case) and installing it _does work_. (Though resolving the environment takes a long time)

You also need to do a 'conda install ffmpeg' in order for the gradio interface to work correctly.

Additionally, AudioLDM automatically sets up a public Gradio share link, this can be disabled by setting 'iface.launch(share=True)' in 'app.py' to 'False'.

**Comment by Fictiverse** [comment]
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

Worked for me

**Comment by rne1223** [comment]
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

worked for me as well

**Comment by Aptronymist** [comment]
It seems like a simple requirements.txt file would sort this out quite easily. Can we get one? It's now October and the same thing is happening.
